# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c99726d28b01ee967ab8513e94541a97db7faf7b0e12f2f8a033848e214968bcd0ad7c0521edd2b7fd9a9427eaedab83254b2758bd4222e20a8d63bdf73a1e07

test:
  secret_key_base: 40b05d44cfa0a24f4a13b2803f858c417e9bef9542cbc41ba229f8dd939f02b799c8caa480abf52d207411257d9725ee9eb0b759e23f733e1a29afe076551902

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
